[build]
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.build]
cmds = ["pnpm run build"]

[phases.postBuild]
cmds = ["pnpm --filter docs run build"]

[start]
cmd = "pnpm start"
